import Image from 'next/image'
import logoLight from '@/public/brand/logo-light.png'
import mark from '@/public/brand/mark.png'

/**
 * Real brand assets, replacing the hand-drawn SVG placeholder.
 *
 * ⚠️ SOURCE FILE NOTES — read before swapping these out.
 *
 * The four supplied files were ALL fully opaque, including the one named
 * "transparentlogolab". Two were JPEGs (a format with no alpha channel at all)
 * and the two PNGs had a solid background baked in. Dropped into this dark
 * header as supplied, every one of them would have rendered as a white or
 * black rectangle around the logo.
 *
 * So `public/brand/*.png` were generated by flood-filling the background from
 * the image border — deliberately NOT by global color matching, which would
 * have eaten the dark navy inside the gradient swoosh. Interior artwork is
 * pixel-identical to the source; only the connected outer background was made
 * transparent, then the canvas was trimmed to content.
 *
 * WHEN YOU HAVE THE VECTOR SOURCE (.ai / .svg / .fig), replace these with SVG.
 * These are 480px-wide rasters — fine at header size on retina, but SVG is
 * sharper at every size and a fraction of the bytes. That is the only upgrade
 * left here.
 *
 * `logo-dark.png` also exists for light backgrounds — invoices, proposals,
 * print, and the light theme if it is ever enabled.
 */

/** Icon only. Header, footer, compact placements. */
export function LogoMark({ className = 'h-8 w-auto' }: { className?: string }) {
  return (
    <Image
      src={mark}
      alt=""
      aria-hidden="true"
      className={className}
      /* priority: this is above the fold in the header on every page, so it
         must not wait for lazy-loading and cause a visible pop-in. */
      priority
      unoptimized
    />
  )
}

/** Full lockup — icon plus "labtech crew" wordmark, white text for dark UI. */
export function Wordmark({ className = 'h-7 w-auto' }: { className?: string }) {
  return (
    <Image
      src={logoLight}
      alt="LabTechCrew"
      className={className}
      priority
      unoptimized
    />
  )
}
